### ISSUE TITLE
Sample Materials page

### ISSUE THREAD

**Issue by emcdevitt** [brainhack-princeton/handbook#56]
I also emailed this info to Paula, but here are the files I've collected for our Sample Material page. I am envisioning different sections (Email Templates, Study Checklists, Participant Instructions/Scripts, Code, Other Useful Resources, etc.) with files hyperlinked below each section. 

e.g., 
Study Checklists
- Checklist 1
- Checklist 2
- Checklist 3

I am attaching non-code files here!
[SubjectEmailReminder.docx](https://github.com/brainhack-princeton/handbook/files/3980731/SubjectEmailReminder.docx)
[Checklist1.docx](https://github.com/brainhack-princeton/handbook/files/3980732/Checklist1.docx)
[Checklist2.docx](https://github.com/brainhack-princeton/handbook/files/3980733/Checklist2.docx)
[Checklist3.docx](https://github.com/brainhack-princeton/handbook/files/3980734/Checklist3.docx)
[ExperimenterScriptandInstructions.docx](https://github.com/brainhack-princeton/handbook/files/3980735/ExperimenterScriptandInstructions.docx)

**Comment by emcdevitt** [comment]
Another file for Email Templates!

[SampleRecruitmentEmailText.docx](https://github.com/brainhack-princeton/handbook/files/3980766/SampleRecruitmentEmailText.docx)

**Comment by emcdevitt** [comment]
@paulapbrooks Here is another doc for the Sample Materials page! This is a script for going over MRI safety procedures with subjects. 
[MRISafetyProceduresScript.docx](https://github.com/brainhack-princeton/handbook/files/4078977/MRISafetyProceduresScript.docx)

**Comment by paulapbrooks** [comment]
@emcdevitt thanks for sending me the new doc! I just made a pull request adding it and will merge it soon after it passes all the checks. Please let me know if you think that things should be in a different order or something :)
