### ISSUE TITLE
Greetings/Tweetings!

### ISSUE THREAD

**Issue by adswa** [brainhack-princeton/handbook#82]
Hi, and greetings from the DataLad handbook team! We were delighted to find out that you put the handbook infrastructure into good use - your handbook is a great collection of knowledge and resources, and we were super happy that the infrastructural backbone is useful for more than just ourselves. :)

With the upcoming 0.13 release of DataLad and the DataLad handbook I'll tweet a bit more about the handbook. I also want to stress that anyone is free to use the Sphinx setup we created as a backbone for their handbook/documentation project just as you did. Would you mind if I include you in my tweet? And how would you want to be cited - would lead author et al., plus link to the handbook (or zenodo, or Github repo?) be fine?

Cheers,
Adina

**Comment by snastase** [comment]
Hi Adina—this sounds great! Our handbook is still very much a work-in-progress, but the scaffold provided by the DataLad handbook was absolutely invaluable! I guess if you're looking for a formal citation, the Brooks et al Zenodo reference makes sense ([link](http://doi.org/10.5281/zenodo.3688789)), but for tweeting purposes, just the handbook URL would be fine too (https://brainhack-princeton.github.io/handbook/). Thanks!

**Comment by adswa** [comment]
Awesome, thanks Sam! I'll close this issue and there will be a tweet citing you people with once datalad 0.13 is out.
